services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    environment:
      # L'hôte cible devient directement le nom du conteneur : mysql-devops
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-devops:3306/test_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root # Ajustez si un mot de passe différent a été défini
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    networks:
      devops-network:
        aliases:
          - backend-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - devops-network

networks:
  devops-network:
    external: true