apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "gestion_projets"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "root"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "admin"
